### ISSUE TITLE
PH crashes with voicememos recording

### ISSUE THREAD

**Issue by joemerlino** [thomasfinch/Priority-Hub#14]
hi! 
I noticed that if you are recording something with the stock voicememos app and then lock your device, when a notification comes in, the entire springboard crashes. I think it's a problem between the tweak and the lockscreen wave animation.
Thanks in advance!

**Comment by thomasfinch** [comment]
I don't believe this is priority hub, I just tested it both with priority hub installed and without it installed and in both cases it just showed the notification as a banner instead of a normal lock screen notification. Maybe you have another tweak that's causing the problem? It could also maybe be a difference between iOS versions, I'm only able to test it on iOS 8.

**Comment by joemerlino** [comment]
i'm sorry, you're absolutely right. It was tinybar. Thanks for the support anyway!
